# Generated by Django 5.2.6 on 2025-10-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_reservation_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='planificacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
