# Generated by Django 5.2.6 on 2025-10-08 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_reservation_planificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='planificacion',
        ),
    ]
