# Generated by Django 5.2.6 on 2025-10-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_profile_birth_date_profile_gender_profile_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='document_type',
            field=models.CharField(choices=[('V', 'V'), ('J', 'J'), ('E', 'E')], default='V', max_length=1),
        ),
    ]
