# Generated by Django 5.2.6 on 2025-10-11 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_profile_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='document_type',
        ),
    ]
