# Generated by Django 5.2.6 on 2025-10-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_profile_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activated_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='plan',
            field=models.CharField(choices=[('basic', '12 clases/mes'), ('premium', '24 clases/mes')], default='basic', max_length=10),
        ),
    ]
