# Generated by Django 5.2.6 on 2025-10-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_profile_activated_on_profile_expires_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
    ]
