# Generated by Django 5.2.6 on 2025-10-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='moneda',
            field=models.CharField(choices=[('VES', 'Bolívares'), ('USD', 'Dólares'), ('COP', 'Pesos')], default='VES', max_length=3),
        ),
    ]
