# Generated by Django 5.2.6 on 2025-10-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_pago_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='creditos',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='pago',
            name='plan',
            field=models.CharField(choices=[('basic', 'Básico'), ('premium', 'Premium')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='plan',
            field=models.CharField(choices=[('basic', 'Básico'), ('premium', 'Premium')], default='basic', max_length=10),
        ),
    ]
