# Generated by Django 5.2.6 on 2025-10-17 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_profile_creditos_alter_pago_plan_alter_profile_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='creditos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LiftResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.CharField(choices=[('Snatch', 'Snatch'), ('Clean & Jerk', 'Clean & Jerk'), ('Back Squat', 'Back Squat'), ('Front Squat', 'Front Squat'), ('Deadlift', 'Deadlift'), ('Bench Press', 'Bench Press')], max_length=50)),
                ('date', models.DateField()),
                ('rounds', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('lb', 'lb')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
