# Generated by Django 5.2.6 on 2025-11-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_pago_correo_usuario_pago_nombre_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liftresult',
            name='movement',
            field=models.CharField(choices=[('Snatch', 'Snatch'), ('Power Snatch', 'Power Snatch'), ('Clean & Jerk', 'Clean & Jerk'), ('Clean', 'Clean'), ('Power Clean', 'Power Clean'), ('Back Squat', 'Back Squat'), ('Front Squat', 'Front Squat'), ('Deadlift', 'Deadlift'), ('Bench Press', 'Bench Press'), ('Push Jerk', 'Push Jerk'), ('Split Jerk', 'Split Jerk'), ('Shoulder Press', 'Shoulder Press')], max_length=50),
        ),
    ]
